M48
; DRILL file KiCad 10.0.4 date 2026-07-13T16:49:02
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-13T16:49:02+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.250
%
G90
G05
T1
X111.72Y-105.05
X111.72Y-117.75
X156.215Y-105.05
X156.215Y-117.75
M30
